coding the html and css  and doing linters error   while making the d…
rotshidzw/portfolio pull request #5
Opened 2022-04-01 11:58 UTC by rotshidzw

desktop vision  of  postfolio  i just added some codes on HTML and CSS  to make  some grid changes on it

2022-04-01 15:52 UTC, ShadyShawkat requested changes
## Hi @rotshidzw, 

Good job so far! 👍🏻 
There are some issues that you still need to work on to go to the next project but you are almost there!

![Image](https://media.giphy.com/media/UdaSUYClr92cjWpeVx/giphy.gif)

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-04-01 15:52 UTC, ShadyShawkat commented on index.html
> +                </div>
- Kindly try and stick to the Figma design as much as possible, which includes:
   - [ ] using the same font style from the Figma design.
   - [ ] matching the element's positions and the spacing around them.

| | Your design | Figma design |
| --- | --- | --- |
| Mobile View | ![image](https://user-images.githubusercontent.com/62290545/161279110-723f5349-d1c0-4515-98b2-9aaad5d68100.png) | ![image](https://user-images.githubusercontent.com/62290545/161279240-86aaf220-b3ad-405f-b0ab-fb20eff25326.png) |
| Desktop View | ![image](https://user-images.githubusercontent.com/62290545/161296281-bc4337ed-f132-4293-8fca-1a5978763857.png) | ![image](https://user-images.githubusercontent.com/62290545/161296375-e9c474c3-4bd3-4a88-8c05-4e21ecf8b90d.png) |

2022-04-01 15:52 UTC, ShadyShawkat commented on index.html
> +        </section>
- [ ] Please remove the extra space on the right in this section. You can easily do that by using the `box-sizing: border-box` property which would make elements' widths appear properly.
- [ ] Please be sure to have proper space on the right and left on this section, this section has very large padding on both sides which ruins its display on width `768px`. Please fix this. 

| Your design | Figma design |
| --- | --- |
| ![image](https://user-images.githubusercontent.com/62290545/161298369-605cc4ba-4f2f-41ad-8d64-a0971dae1812.png) | ![image](https://user-images.githubusercontent.com/62290545/161298464-e8622bac-3291-4ef2-a4d8-b461b9d49e32.png) |

2022-04-01 15:52 UTC, ShadyShawkat commented on index.html
> +                </div>
- [ ] Kindly fix the button position to match the Figma design.
- [ ] Please make sure that the list of technologies in each card display properly and have the same font style and color to match the Figma design. (You can use the `text-decoration` property on the `ul` elements to remove the bullet points)

| Your design | Figma design |
| --- | --- |
| ![image](https://user-images.githubusercontent.com/62290545/161284669-c9ed984d-6935-4dc5-93d6-7c8f5c120caa.png) | ![image](https://user-images.githubusercontent.com/62290545/161284800-8c145a7d-9dd0-40a4-962d-fb6e853d6081.png) |

2022-04-01 15:52 UTC, ShadyShawkat commented on style.css
> +  }
- [ ] [OPTIONAL] Kindly remember the difference between `margin` and `padding`. You can read about the difference [here](https://blog.hubspot.com/website/css-margin-vs-padding?msclkid=77294733b1c911ecbcf514a7c1e86486). Also, you can use them with percentages instead of fixed values for proper display.

2022-04-01 15:52 UTC, ShadyShawkat commented on index.html
> +        </header>
- [ ] Kindly remove the extra space on the top of the header section in the desktop view, to match the Figma design.

| Your design | Figma design |
| --- | --- |
| ![image](https://user-images.githubusercontent.com/62290545/161293391-00fe75b0-aeb6-4a88-b219-f533306ed22b.png) | ![image](https://user-images.githubusercontent.com/62290545/161293580-abddbbcf-008c-4f80-8618-6881c149b3b5.png) |

2022-04-01 15:52 UTC, ShadyShawkat commented on index.html
> +            <h3>LET’S CONNECT</h3>
- [ ] Please make sure this section displays properly to match the Figma design. This is caused by setting large fixed padding right which is too large on width `768px`.

| Your design | Figma design |
| --- | --- |
| ![image](https://user-images.githubusercontent.com/62290545/161294117-259f2efa-473c-44ab-83bc-83fb72409526.png) | ![image](https://user-images.githubusercontent.com/62290545/161294253-1e01e02b-2a37-4b6b-9d36-e68113ab8e2f.png) |

2022-04-01 15:52 UTC, ShadyShawkat commented on index.html
> +                </div>
- [ ] Kindly make sure that the project cards display properly on width `768px` to match the Figma design. 

| Your design | Figma design |
| --- | --- |
| ![image](https://user-images.githubusercontent.com/62290545/161294832-06308c45-40fd-42bf-a50c-dd7e37d25a0d.png) | ![image](https://user-images.githubusercontent.com/62290545/161294899-cbdd229b-ae1e-457f-be00-04a937494a2c.png) |

2022-04-02 12:29 UTC, prolajumokeoni requested changes
Hi @rotshidzw, 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.

## Highlights
✔️ No linter errors
✔️ Github flow was correctly used
 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
- Kindly add a short  descriptive pull request title explaining changes you made in your pull request eg: "build-desktop-version" or "porfolio-desktop-version" 

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification @prolajumokeoni.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-04-02 12:29 UTC, prolajumokeoni commented on index.html
>    <body>
- [ ] Kindly fix image links: currently all images in your projects are not visible reason could be the links path changed, here is a video I recorded, please fix this ⬇️ 


https://user-images.githubusercontent.com/69638013/161382415-1109abc0-9417-42ea-993f-0e4b57eb5d63.mp4

2022-04-02 12:29 UTC, prolajumokeoni commented on index.html
> +    <section class="about" id="about">
Figma Design          |  Your design     
:-------------------------:|:-------------------------:
![Screenshot_37](https://user-images.githubusercontent.com/69638013/161382648-f1927286-98d4-4e66-82c1-f0691065b451.png) |  ![Screenshot_36](https://user-images.githubusercontent.com/69638013/161382641-2e4aa445-cae8-432c-ad48-431a8e844ce1.png)

- [ ] In this section you have two blocks; The left one takes 40% which has the tag "first-part" and the right one the remaining 60%  which has the tag "skills-list" of the page's width
- [ ] Kindly ensure the  contents of each of them are aligned to the right
- [ ] kindly adjust the languages header to be just like the Figma design, It should be next to the about header 🤝 
- Just as the previous reviewer suggested try to make your design look like the original design as much as possible please add the missing icons and images  👍🏿

2022-04-02 12:59 UTC, rotshidzw commented
i  added all my pictures  that crushed during my linters process

2022-04-02 13:08 UTC, omar-labana commented
@rotshidzw nice work actually, one of the very clear designs

2022-04-02 13:08 UTC, omar-labana commented
# **Approved ✔️**

Hi @rotshidzw,

Congratulations on completing this project! 👏🏼 🎉

You have correctly implemented all of the requirements📃 correctly and without any errors⚠️ or bugs🪲.

Cheers and good luck in your next milestones! 🍀

Feel free to leave any questions or comments in the PR thread(don't forget to tag me 😄) if something is not 100% clear.

---
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-04-02 13:16 UTC, merged